name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest-l
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clear space to remove unused folders
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update the ToC in the README.md
        run: npx markdown-toc README.md -i

      - name: Semantic release
        uses: codfish/semantic-release-action@v3
        id: semanticrelease
        with:
          additional-packages: |
            ['@semantic-release/git', '@semantic-release/changelog', '@semantic-release/exec']
        env:
          GITHUB_TOKEN: ${{ secrets.BLIBLA_SEMANTIC_RELEASE }}

      - name: Set environment variables
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        run: |
          echo "DOCKERHUB_REPO=${{ vars.DOCKERHUB_REPO }}" >> $GITHUB_ENV
          echo "DOCKERHUB_IMG=${{ vars.DOCKERHUB_IMG }}" >> $GITHUB_ENV
          echo "HUGGINGFACE_ACCESS_TOKEN=${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ steps.semanticrelease.outputs.release-version }}" >> $GITHUB_ENV

      - name: Build and push the images to Docker Hub
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        uses: docker/bake-action@v2
        with:
          push: true
          set: |
            *.args.DOCKERHUB_REPO=${{ env.DOCKERHUB_REPO }}
            *.args.DOCKERHUB_IMG=${{ env.DOCKERHUB_IMG }}
            *.args.RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            *.args.HUGGINGFACE_ACCESS_TOKEN=${{ env.HUGGINGFACE_ACCESS_TOKEN }}

      - name: Update description on Docker Hub
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMG }}
# Modified 2024-06-13
# Modified 2024-09-12
# Modified 2025-02-11
# Modified 2025-02-19
# Modified 2025-02-28
# Modified 2025-05-05
# Modified 2025-07-23
# Modified 2025-09-29
# Modified 2025-12-17
# Modified 2024-03-16
# Modified 2024-03-17
# Modified 2024-05-28
# Modified 2024-06-17
# Modified 2024-06-20
# Modified 2024-08-08
# Modified 2024-08-11
# Modified 2024-10-21
# Modified 2024-12-21
# Modified 2024-12-24
# Modified 2025-01-15
# Modified 2025-06-11
# Modified 2025-06-17
# Modified 2025-09-16
# Modified 2025-10-14
# Modified 2024-02-19
# Modified 2024-02-24
# Modified 2024-02-29
# Modified 2024-04-30
# Modified 2024-07-01
# Modified 2024-08-04
# Modified 2024-10-08
# Modified 2024-10-13
# Modified 2024-12-15
# Modified 2024-12-17
# Modified 2025-01-13
# Modified 2025-04-04
# Modified 2025-04-18
# Modified 2025-04-22
# Modified 2025-05-02
# Modified 2025-06-25
# Modified 2025-08-29
# Modified 2025-09-02
# Modified 2025-12-12
# Modified 2024-02-20
# Modified 2024-03-29
# Modified 2024-04-05
# Modified 2024-06-02
# Modified 2024-08-06
# Modified 2024-08-18
# Modified 2024-10-07
# Modified 2024-10-09
# Modified 2024-10-22
# Modified 2024-10-27
# Modified 2024-11-06
